#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Passcode.Google.Resource", IsApplication=false)]

namespace Passcode.Google
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int passcode_cycle7 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int passcode_shake = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int cols = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int rows = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int passcode_buttoncolors = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int passcode_buttonpressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int passcode_buttonstates = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int passcode_roundedbutton = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public static int passcode_button0 = 2131165197;
			
			// aapt resource value: 0x7f070003
			public static int passcode_button1 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public static int passcode_button2 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public static int passcode_button3 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public static int passcode_button4 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int passcode_button5 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public static int passcode_button6 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public static int passcode_button7 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public static int passcode_button8 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public static int passcode_button9 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public static int passcode_cancel = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public static int passcode_clear = 2131165196;
			
			// aapt resource value: 0x7f070000
			public static int passcode_container = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int passcode_header = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int passcode_toplayout = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int passcode_main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int PasscodeHeader = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public static int passcode_cancel = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int passcode_clear = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060006
			public static int PasscodeContainer = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public static int PasscodeContainer_Large = 2131099661;
			
			// aapt resource value: 0x7f060014
			public static int PasscodeContainer_XLarge = 2131099668;
			
			// aapt resource value: 0x7f060001
			public static int PasscodeFillableLayout = 2131099649;
			
			// aapt resource value: 0x7f060007
			public static int PasscodeFillableLayout_Large = 2131099655;
			
			// aapt resource value: 0x7f06000e
			public static int PasscodeFillableLayout_XLarge = 2131099662;
			
			// aapt resource value: 0x7f060000
			public static int PasscodeHeader = 2131099648;
			
			// aapt resource value: 0x7f060009
			public static int PasscodeHeader_Large = 2131099657;
			
			// aapt resource value: 0x7f060010
			public static int PasscodeHeader_XLarge = 2131099664;
			
			// aapt resource value: 0x7f060002
			public static int PasscodeNumberButton = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public static int PasscodeNumberButton_Large = 2131099658;
			
			// aapt resource value: 0x7f060011
			public static int PasscodeNumberButton_XLarge = 2131099665;
			
			// aapt resource value: 0x7f060005
			public static int PasscodeNumberLayout = 2131099653;
			
			// aapt resource value: 0x7f060008
			public static int PasscodeNumberLayout_Large = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public static int PasscodeNumberLayout_XLarge = 2131099663;
			
			// aapt resource value: 0x7f060003
			public static int PasscodeSmallButton = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public static int PasscodeSmallButton_Large = 2131099660;
			
			// aapt resource value: 0x7f060013
			public static int PasscodeSmallButton_XLarge = 2131099667;
			
			// aapt resource value: 0x7f060004
			public static int PasscodeSmallCircle = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public static int PasscodeSmallCircle_Large = 2131099659;
			
			// aapt resource value: 0x7f060012
			public static int PasscodeSmallCircle_XLarge = 2131099666;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] squarelayout = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public static int squarelayout_cols = 1;
			
			// aapt resource value: 0
			public static int squarelayout_rows = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
