#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Passcode.Android.Customized.Resource", IsApplication=true)]

namespace Passcode.Android.Customized
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Passcode.Google.Resource.Animation.passcode_cycle7 = global::Passcode.Android.Customized.Resource.Animation.passcode_cycle7;
			global::Passcode.Google.Resource.Animation.passcode_shake = global::Passcode.Android.Customized.Resource.Animation.passcode_shake;
			global::Passcode.Google.Resource.Attribute.cols = global::Passcode.Android.Customized.Resource.Attribute.cols;
			global::Passcode.Google.Resource.Attribute.rows = global::Passcode.Android.Customized.Resource.Attribute.rows;
			global::Passcode.Google.Resource.Drawable.passcode_buttoncolors = global::Passcode.Android.Customized.Resource.Drawable.passcode_buttoncolors;
			global::Passcode.Google.Resource.Drawable.passcode_buttonpressed = global::Passcode.Android.Customized.Resource.Drawable.passcode_buttonpressed;
			global::Passcode.Google.Resource.Drawable.passcode_buttonstates = global::Passcode.Android.Customized.Resource.Drawable.passcode_buttonstates;
			global::Passcode.Google.Resource.Drawable.passcode_roundedbutton = global::Passcode.Android.Customized.Resource.Drawable.passcode_roundedbutton;
			global::Passcode.Google.Resource.Id.passcode_button0 = global::Passcode.Android.Customized.Resource.Id.passcode_button0;
			global::Passcode.Google.Resource.Id.passcode_button1 = global::Passcode.Android.Customized.Resource.Id.passcode_button1;
			global::Passcode.Google.Resource.Id.passcode_button2 = global::Passcode.Android.Customized.Resource.Id.passcode_button2;
			global::Passcode.Google.Resource.Id.passcode_button3 = global::Passcode.Android.Customized.Resource.Id.passcode_button3;
			global::Passcode.Google.Resource.Id.passcode_button4 = global::Passcode.Android.Customized.Resource.Id.passcode_button4;
			global::Passcode.Google.Resource.Id.passcode_button5 = global::Passcode.Android.Customized.Resource.Id.passcode_button5;
			global::Passcode.Google.Resource.Id.passcode_button6 = global::Passcode.Android.Customized.Resource.Id.passcode_button6;
			global::Passcode.Google.Resource.Id.passcode_button7 = global::Passcode.Android.Customized.Resource.Id.passcode_button7;
			global::Passcode.Google.Resource.Id.passcode_button8 = global::Passcode.Android.Customized.Resource.Id.passcode_button8;
			global::Passcode.Google.Resource.Id.passcode_button9 = global::Passcode.Android.Customized.Resource.Id.passcode_button9;
			global::Passcode.Google.Resource.Id.passcode_cancel = global::Passcode.Android.Customized.Resource.Id.passcode_cancel;
			global::Passcode.Google.Resource.Id.passcode_clear = global::Passcode.Android.Customized.Resource.Id.passcode_clear;
			global::Passcode.Google.Resource.Id.passcode_container = global::Passcode.Android.Customized.Resource.Id.passcode_container;
			global::Passcode.Google.Resource.Id.passcode_header = global::Passcode.Android.Customized.Resource.Id.passcode_header;
			global::Passcode.Google.Resource.Id.passcode_toplayout = global::Passcode.Android.Customized.Resource.Id.passcode_toplayout;
			global::Passcode.Google.Resource.Layout.passcode_main = global::Passcode.Android.Customized.Resource.Layout.passcode_main;
			global::Passcode.Google.Resource.String.PasscodeHeader = global::Passcode.Android.Customized.Resource.String.PasscodeHeader;
			global::Passcode.Google.Resource.String.library_name = global::Passcode.Android.Customized.Resource.String.library_name;
			global::Passcode.Google.Resource.String.passcode_cancel = global::Passcode.Android.Customized.Resource.String.passcode_cancel;
			global::Passcode.Google.Resource.String.passcode_clear = global::Passcode.Android.Customized.Resource.String.passcode_clear;
			global::Passcode.Google.Resource.Style.PasscodeContainer = global::Passcode.Android.Customized.Resource.Style.PasscodeContainer;
			global::Passcode.Google.Resource.Style.PasscodeContainer_XLarge = global::Passcode.Android.Customized.Resource.Style.PasscodeContainer_XLarge;
			global::Passcode.Google.Resource.Style.PasscodeFillableLayout = global::Passcode.Android.Customized.Resource.Style.PasscodeFillableLayout;
			global::Passcode.Google.Resource.Style.PasscodeFillableLayout_Large = global::Passcode.Android.Customized.Resource.Style.PasscodeFillableLayout_Large;
			global::Passcode.Google.Resource.Style.PasscodeFillableLayout_XLarge = global::Passcode.Android.Customized.Resource.Style.PasscodeFillableLayout_XLarge;
			global::Passcode.Google.Resource.Style.PasscodeHeader = global::Passcode.Android.Customized.Resource.Style.PasscodeHeader;
			global::Passcode.Google.Resource.Style.PasscodeHeader_Large = global::Passcode.Android.Customized.Resource.Style.PasscodeHeader_Large;
			global::Passcode.Google.Resource.Style.PasscodeHeader_XLarge = global::Passcode.Android.Customized.Resource.Style.PasscodeHeader_XLarge;
			global::Passcode.Google.Resource.Style.PasscodeNumberButton = global::Passcode.Android.Customized.Resource.Style.PasscodeNumberButton;
			global::Passcode.Google.Resource.Style.PasscodeNumberButton_Large = global::Passcode.Android.Customized.Resource.Style.PasscodeNumberButton_Large;
			global::Passcode.Google.Resource.Style.PasscodeNumberButton_XLarge = global::Passcode.Android.Customized.Resource.Style.PasscodeNumberButton_XLarge;
			global::Passcode.Google.Resource.Style.PasscodeNumberLayout = global::Passcode.Android.Customized.Resource.Style.PasscodeNumberLayout;
			global::Passcode.Google.Resource.Style.PasscodeNumberLayout_Large = global::Passcode.Android.Customized.Resource.Style.PasscodeNumberLayout_Large;
			global::Passcode.Google.Resource.Style.PasscodeNumberLayout_XLarge = global::Passcode.Android.Customized.Resource.Style.PasscodeNumberLayout_XLarge;
			global::Passcode.Google.Resource.Style.PasscodeSmallButton = global::Passcode.Android.Customized.Resource.Style.PasscodeSmallButton;
			global::Passcode.Google.Resource.Style.PasscodeSmallButton_Large = global::Passcode.Android.Customized.Resource.Style.PasscodeSmallButton_Large;
			global::Passcode.Google.Resource.Style.PasscodeSmallButton_XLarge = global::Passcode.Android.Customized.Resource.Style.PasscodeSmallButton_XLarge;
			global::Passcode.Google.Resource.Style.PasscodeSmallCircle = global::Passcode.Android.Customized.Resource.Style.PasscodeSmallCircle;
			global::Passcode.Google.Resource.Style.PasscodeSmallCircle_Large = global::Passcode.Android.Customized.Resource.Style.PasscodeSmallCircle_Large;
			global::Passcode.Google.Resource.Style.PasscodeSmallCircle_XLarge = global::Passcode.Android.Customized.Resource.Style.PasscodeSmallCircle_XLarge;
			global::Passcode.Google.Resource.Styleable.squarelayout = global::Passcode.Android.Customized.Resource.Styleable.squarelayout;
			global::Passcode.Google.Resource.Styleable.squarelayout_cols = global::Passcode.Android.Customized.Resource.Styleable.squarelayout_cols;
			global::Passcode.Google.Resource.Styleable.squarelayout_rows = global::Passcode.Android.Customized.Resource.Styleable.squarelayout_rows;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int passcode_cycle7 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int passcode_shake = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cols = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int rows = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_state_normal = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_state_pressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_text_colors = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int passcode_buttoncolors = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int passcode_buttonpressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int passcode_buttonstates = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int passcode_buttonstates_custom = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int passcode_roundedbutton = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int myButton = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int passcode_button0 = 2131165198;
			
			// aapt resource value: 0x7f070004
			public const int passcode_button1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int passcode_button2 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int passcode_button3 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int passcode_button4 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int passcode_button5 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int passcode_button6 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int passcode_button7 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int passcode_button8 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int passcode_button9 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int passcode_cancel = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int passcode_clear = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int passcode_container = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int passcode_header = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int passcode_toplayout = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int passcode_main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int PasscodeHeader = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int hello = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int passcode_cancel = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int passcode_clear = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060006
			public const int PasscodeContainer = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int PasscodeContainer_XLarge = 2131099667;
			
			// aapt resource value: 0x7f060001
			public const int PasscodeFillableLayout = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int PasscodeFillableLayout_Large = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int PasscodeFillableLayout_XLarge = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int PasscodeHeader = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int PasscodeHeader_Large = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int PasscodeHeader_XLarge = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int PasscodeNumberButton = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int PasscodeNumberButton_Large = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int PasscodeNumberButton_XLarge = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int PasscodeNumberLayout = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int PasscodeNumberLayout_Large = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int PasscodeNumberLayout_XLarge = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int PasscodeSmallButton = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int PasscodeSmallButton_Large = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int PasscodeSmallButton_XLarge = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int PasscodeSmallCircle = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int PasscodeSmallCircle_Large = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int PasscodeSmallCircle_XLarge = 2131099665;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] squarelayout = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int squarelayout_cols = 1;
			
			// aapt resource value: 0
			public const int squarelayout_rows = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
